### PR TITLE
make deposit_count a uint64

### PR DESCRIPTION
**Pull request by MrChico**

### CODE REVIEW

**Comment by axic** [comment]
@daejunpark advised against this, postponing.

**Comment by leonardoalt** [comment]
What's the idea behind postponing?
Wouldn't it be better to just merge it into a branch `wanted_but_not_recommended_by_RV`?

**Comment by daejunpark** [comment]
I guess the idea is to revisit this once the initial run of FV is passed, so that we can progress incrementally but steadily.

BTW, just to be clear, my suggestion was based on the extra complexity when accessing the value in the storage by this change (mentioned by @chriseth).

**Comment by axic** [comment]
> I guess the idea is to revisit this once the initial run of FV is passed, so that we can progress incrementally but steadily.

@daejunpark @MrChico What is the verdict about this now?

**Comment by MrChico** [comment]
I don't feel like the value of this change is high enough to warrant a bytecode change at this point

**Comment by daejunpark** [comment]
I agree with @MrChico.

**Comment by axic** [comment]
Can we close this then?

**Comment by MrChico** [comment]
Ya

**Pull request closed without merging**
