### PR TITLE
Relicense from Apache2.0 to CC0-1.0

### PR DESCRIPTION
**Pull request by hwwhww**
To port the deposit contract and tests to [eth2.0-specs](https://github.com/ethereum/eth2.0-specs) repository, this PR relicense from Apache2.0 to CC0-1.0.

It requires the authors to sign an approval here.

@axic @MrChico @chriseth

### CODE REVIEW

**Comment by MrChico** [comment]
I consent

**Comment by hwwhww** [comment]
Ah, I didn't know that changing the license would also modify bytecode metadata. Would that be considered to break the audited report?

/cc @daejunpark

**Review by chriseth — APPROVED** [review]
I agree with the license change to CC0

**Comment by daejunpark** [comment]
@hwwhww No, any metadata change shouldn't break the formal verification proof. But just to make sure, I'll rerun the proof once the bytecode is finalized, and update the report as well. Please let me know when that happens. Thanks!

**Comment by axic** [comment]
> Ah, I didn't know that changing the license would also modify bytecode metadata. Would that be considered to break the audited report?

It does because the hashes of the sources are included in the metadata. Any change, even whitespace, in the source will result in this.

**Comment by axic** [comment]
Since due to the metadata change the verification needs to be re-run, could we merge #36 as well prior to verification? #36 means changing to Solidity 0.6.11 which produces identical bytecode, but the metadata is different (more usable).

**Comment by daejunpark** [comment]
@axic Sure, please just let me know once the bytecode is finalized. Thanks!

**Comment by hwwhww** [comment]
@axic I uploaded the bytecode. Can we merge it first?

**Comment by axic** [comment]
Sorry, did not read the message here and started merging the others :(

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
@daejunpark merged all the agreed ones and tagged it [`r2`](https://github.com/axic/eth2-deposit-contract/releases/tag/r2). Could you rerun the verification?

**Comment by daejunpark** [comment]
@axic Sorry for the delay. It has been successfully rerun now: https://github.com/runtimeverification/deposit-contract-verification/pull/17

**Comment by axic** [comment]
Great news, thank you @daejunpark!

cc @hwwhww @djrtwo

**Pull request merged**
